kind: pipeline
type: docker
name: java-image-build

# Trigger conditions
trigger:
  branch:
    - '23'
  event:
    - pull_request

# Build the jdk and jre docker images for amd64 architecture
steps:
  # Build JDK image
  - name: docker-build-jdk
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    when:
      branch:
        - '23'
      when:
        - push
    settings:
      platforms:
        - linux/amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: jdk/Dockerfile
      repo: kernel528/jdk
      tags:
        - jdk-latest
        - jdk23.0.1-11
        - jdk23.0.1-11-drone-build-${DRONE_BUILD_NUMBER}

  # Build JRE Image
  - name: docker-build-jre
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    when:
      branch:
        - '23'
      when:
        - push
    settings:
      platforms:
        - linux/amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: jre/Dockerfile
      repo: kernel528/jre
      tags:
        - jre-latest
        - jre23.0.1-11
        - jre23.0.1-11-drone-build-${DRONE_BUILD_NUMBER}

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts

---

kind: pipeline
type: docker
name: java-image-test

# Trigger conditions
trigger:
  branch:
    - main
  event:
    - push

# Test java-docker images
steps:
  # Test JDK Image
  - name: docker-test-jdk
    image: kernel528/jdk:jdk-latest
    when:
      branch:
        - main
      when:
        - push
    commands:
      - "uname -a"
      - "cat /etc/os-release"
      - "java -version"
      - "javac src/hello-world/HelloWorld.java"
      - "java -classpath src/hello-world HelloWorld"

  # Test JRE Image
  - name: docker-test-jre
    image: kernel528/jre:jre-latest
    when:
      branch:
        - main
      when:
        - push
    commands:
      - "uname -a"
      - "cat /etc/os-release"
      - "java -version"
      - "java -classpath src/hello-world HelloWorld"

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts

---

kind: pipeline
type: docker
name: java-image-tag

trigger:
  event:
    - tag

# Build the jdk and jre docker images for amd64 architecture
steps:
  # Build JDK image
  - name: docker-build-jdk
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    when:
      event:
        - tag
    settings:
      platforms:
        - linux/amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: jdk/Dockerfile
      repo: kernel528/jdk
      tags:
        - jdk-${DRONE_TAG}

  # Build JRE Image
  - name: docker-build-jre
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    when:
      event:
        - tag
    settings:
      platforms:
        - linux/amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: jre/Dockerfile
      repo: kernel528/jre
      tags:
        - jre-${DRONE_TAG}

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts