kind: pipeline
type: docker
name: java-image-build

# Trigger conditions
trigger:
  branch:
    - '21'
  event:
    - pull_request

# Build the jdk and jre docker images for amd64 architecture
steps:
  # Build JDK image
  - name: docker-build-jdk
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    when:
      branch:
        - '21'
      when:
        - push
    settings:
      platforms:
        - linux/amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: jdk/Dockerfile
      repo: kernel528/java
      tags:
        - jdk-latest
        - jdk21.0.5-11
        - jdk21.0.5-11-drone-build-${DRONE_BUILD_NUMBER}

  # Build JRE Image
  - name: docker-build-jre
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    when:
      branch:
        - '21'
      when:
        - push
    settings:
      platforms:
        - linux/amd64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: jre/Dockerfile
      repo: kernel528/java
      tags:
        - jre-latest
        - jre21.0.5-11
        - jre21.0.5-11-drone-build-${DRONE_BUILD_NUMBER}

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts

---

kind: pipeline
type: docker
name: java-image-test

# Trigger conditions
trigger:
  branch:
    - main
  event:
    - push
    - tag

# Test java-docker images
steps:
  # Test JDK Image
  - name: docker-test-jdk
    image: kernel528/java:jdk-latest
    when:
      branch:
        - main
      when:
        - push
    commands:
      - "uname -a"
      - "java -version"
      - "javac src/hello-world/HelloWorld.java"
      - "java -classpath src/hello-world HelloWorld"

  # Test JRE Image
  - name: docker-test-jre
    image: kernel528/java:jre-latest
    when:
      branch:
        - main
      when:
        - push
    commands:
      - "uname -a"
      - "java -version"
      - "java -classpath src/hello-world HelloWorld"

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts