kind: pipeline
type: docker
name: java-image-build

trigger:
  branch:
    - '21-arm64'
  event:
    - pull_request

steps:
  # Enable QEMU for multi-arch builds
  - name: setup-qemu
    image: tonistiigi/binfmt
    privileged: true

  # Set up Docker Buildx
  - name: setup-buildx
    image: docker:24.0.2
    privileged: true
    environment:
      DOCKER_HOST: tcp://docker:2375
    commands:
      - docker buildx create --use
      - docker buildx inspect --bootstrap

  # Build JDK image
  - name: docker-build-jdk
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
      DOCKER_HOST: tcp://docker:2375
    when:
      branch:
        - '21-arm64'
      event:
        - push
    settings:
      platforms:
        - linux/arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: jdk/Dockerfile
      repo: kernel528/jdk
      use_buildx: true
      tags:
        - jdk-latest-arm64
        - jdk21.0.5-11-arm64
        - jdk21.0.5-11-drone-build-${DRONE_BUILD_NUMBER}-arm64

services:
  - name: docker
    image: docker:dind
    privileged: true

---

kind: pipeline
type: docker
name: java-image-test

trigger:
  branch:
    - main-arm64
  event:
    - push

steps:
  - name: setup-qemu
    image: tonistiigi/binfmt
    privileged: true

  - name: setup-buildx
    image: docker:24.0.2
    privileged: true
    environment:
      DOCKER_HOST: tcp://docker:2375
    commands:
      - docker buildx create --use
      - docker buildx inspect --bootstrap

  - name: docker-test-jdk
    image: kernel528/jdk:jdk-latest-arm64
    when:
      branch:
        - main-arm64
      event:
        - push
    commands:
      - "uname -a"
      - "cat /etc/os-release"
      - "java -version"
      - "javac src/hello-world/HelloWorld.java"
      - "java -classpath src/hello-world HelloWorld"

services:
  - name: docker
    image: docker:dind
    privileged: true

---

kind: pipeline
type: docker
name: java-image-tag

trigger:
  event:
    - tag

steps:
  - name: setup-qemu
    image: tonistiigi/binfmt
    privileged: true

  - name: setup-buildx
    image: docker:24.0.2
    privileged: true
    environment:
      DOCKER_HOST: tcp://docker:2375
    commands:
      - docker buildx create --use
      - docker buildx inspect --bootstrap

  - name: docker-build-jdk
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
      DOCKER_HOST: tcp://docker:2375
    when:
      event:
        - tag
    settings:
      platforms:
        - linux/arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: jdk/Dockerfile
      repo: kernel528/jdk
      use_buildx: true
      tags:
        - jdk-${DRONE_TAG}-arm64

# 🛠 Services for Docker-in-Docker
services:
  - name: docker
    image: docker:dind
    privileged: true