kind: pipeline
type: docker
name: java-image-build

# Trigger conditions
trigger:
  branch:
    - '21-arm64'
  event:
    - pull_request

# Build the jdk and jre docker images for arm64 architecture
steps:
  # Build JDK image
  - name: setup-qemu
    image: multiarch/qemu-user-static
    privileged: true
    commands:
      - /usr/bin/qemu-system-arm --version

  - name: docker-build-jdk
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    when:
      branch:
        - '21-arm64'
      when:
        - push
    settings:
      platforms:
        - linux/arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: jdk/Dockerfile
      repo: kernel528/jdk
      tags:
        - jdk-latest-arm64
        - jdk21.0.5-11-arm64
        - jdk21.0.5-11-drone-build-${DRONE_BUILD_NUMBER}-arm64

  # Build JRE Image
  - name: docker-build-jre
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    when:
      branch:
        - '21-arm64'
      when:
        - push
    settings:
      platforms:
        - linux/arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: jre/Dockerfile
      repo: kernel528/jre
      tags:
        - jre-latest-arm64
        - jre21.0.5-11-arm64
        - jre21.0.5-11-drone-build-${DRONE_BUILD_NUMBER}-arm64

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts

---

kind: pipeline
type: docker
name: java-image-test

# Trigger conditions
trigger:
  branch:
    - main-arm64
  event:
    - push

# Test java-docker images
steps:
  # Test JDK Image
  - name: setup-qemu
    image: multiarch/qemu-user-static
    privileged: true
    commands:
      - /usr/bin/qemu-system-arm --version

  - name: docker-test-jdk
    image: kernel528/jdk:jdk-latest-arm64
    when:
      branch:
        - main-arm64
      when:
        - push
    commands:
      - "uname -a"
      - "cat /etc/os-release"
      - "java -version"
      - "javac src/hello-world/HelloWorld.java"
      - "java -classpath src/hello-world HelloWorld"

  # Test JRE Image
  - name: docker-test-jre
    image: kernel528/jre:jre-latest-arm64
    when:
      branch:
        - main-arm64
      when:
        - push
    commands:
      - "uname -a"
      - "cat /etc/os-release"
      - "java -version"
      - "java -classpath src/hello-world HelloWorld"

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts

---

kind: pipeline
type: docker
name: java-image-tag

trigger:
  event:
    - tag

# Build the jdk and jre docker images for arm64 architecture
steps:
  # Build JDK image
  - name: setup-qemu
    image: multiarch/qemu-user-static
    privileged: true
    commands:
      - /usr/bin/qemu-system-arm --version

  - name: docker-build-jdk
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    when:
      event:
        - tag
    settings:
      platforms:
        - linux/arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: jdk/Dockerfile
      repo: kernel528/jdk
      tags:
        - jdk-${DRONE_TAG}-arm64

  # Build JRE Image
  - name: docker-build-jre
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    when:
      event:
        - tag
    settings:
      platforms:
        - linux/arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: jre/Dockerfile
      repo: kernel528/jre
      tags:
        - jre-${DRONE_TAG}-arm64

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts