kind: pipeline
type: docker
name: java-image-build

# Trigger conditions
trigger:
  branch:
    - '21'
    - main
  event:
    - custom
    - push
    - pull_request

# Pipeline steps
steps:

  # Build JDK images
  - name: docker-build-jdk
    image: plugins/docker
    when:
      branch:
        - '21'
      when:
        - push
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: jdk/Dockerfile
      repo: kernel528/java
      tags:
        - jdk-latest
        - jdk21.0.5+11
        - jdk21.0.5+11-${DRONE_COMMIT:0:8}-drone-build-${DRONE_BUILD_NUMBER}

  # Build JRE Image
  - name: docker-build-jre
    image: plugins/docker
    when:
      branch:
        - '21'
      when:
        - push
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: jre/Dockerfile
      repo: kernel528/java
      tags:
        - jre-latest
        - jre21.0.5+11
        - jre21.0.5+11-${DRONE_COMMIT:0:8}-drone-build-${DRONE_BUILD_NUMBER}

  # Test images
  - name: docker-test
    image: kernel528/java:jdk-latest
    when:
      branch:
        - main
      when:
        - push
    commands:
      - "uname -a"
      - "java -version"

  # Slack notification
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts
    when:
      status:
        - failure
        - success